name: check

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        version: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
        ghc-version: ['9.12.2']
        cabal: ['latest']

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@v1

      - name: Check Moonbit Version
        run: |
          moon version --all

      - name: Setup Haskell
        uses: haskell-actions/setup@v2.8.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Build
        run: |
          cabal build

      - name: Test
        run: |
          cabal test
